/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import bd20191.Cliente;
import bd20191.CriarBancoSQlite;
import bd20191.Restaurante;
import conexoes.ConexaoSQlite;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Luiz Cardoso
 */
public class TelaLoguin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoguin
     */
    public TelaLoguin() {
        initComponents();
        ConexaoSQlite conexaoSQlite = new ConexaoSQlite();
        CriarBancoSQlite criarBancoSQLite = new CriarBancoSQlite(conexaoSQlite);

        criarBancoSQLite.criarTabelaCliente();
        criarBancoSQLite.criarTabelaPedido();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBack = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLoguinC = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtLoguin = new javax.swing.JTextField();
        lblLoguin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();
        passSenha = new javax.swing.JPasswordField();
        btnLoguinR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/f37aaf2e9a0705d904b90d2216d3e460.jpg"))); // NOI18N

        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/f37aaf2e9a0705d904b90d2216d3e460.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loguin");
        setBackground(new java.awt.Color(255, 0, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        btnLoguinC.setText("Logar Cliente");
        btnLoguinC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoguinCActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoguinC);
        btnLoguinC.setBounds(20, 300, 140, 21);

        btnCadastro.setText("Cadastro Cliente");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastro);
        btnCadastro.setBounds(20, 420, 160, 21);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 0));
        jLabel1.setText("Ci Food");
        jLabel1.setIconTextGap(5);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 110, 101, 38);

        txtLoguin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoguinActionPerformed(evt);
            }
        });
        getContentPane().add(txtLoguin);
        txtLoguin.setBounds(20, 180, 250, 30);

        lblLoguin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLoguin.setText("Email:");
        getContentPane().add(lblLoguin);
        lblLoguin.setBounds(20, 160, 56, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Senha: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 220, 60, 14);

        jButton1.setText("Cadastro Restaurante");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 450, 160, 21);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(492, 6, 31, 0);
        getContentPane().add(lblFundo);
        lblFundo.setBounds(37, 0, 31, 0);

        passSenha.setSelectionColor(new java.awt.Color(255, 255, 255));
        passSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(passSenha);
        passSenha.setBounds(20, 240, 250, 30);

        btnLoguinR.setText("Logar Restaurante");
        btnLoguinR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoguinRActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoguinR);
        btnLoguinR.setBounds(20, 330, 140, 21);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delivery-man-with-box-postman-design-isolated-on-white-background-courier-in-hat-and-uniform-with-package-vector.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 690, 500);

        setSize(new java.awt.Dimension(701, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoguinCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoguinCActionPerformed
        // TODO add your handling code here:
        ConexaoSQlite conexaoSQlite = new ConexaoSQlite();
        conexaoSQlite.conectar();

        ResultSet resultSet = null;
        PreparedStatement pstmt = null;

        String sql1 = "SELECT *"
                + " FROM tbl_cliente"
                + " WHERE email = ?"
                + " AND senha = ?";

        try {

            pstmt = conexaoSQlite.criarPreparedStatement(sql1);
            pstmt.setString(1, txtLoguin.getText());
            pstmt.setString(2, passSenha.getText());

            resultSet = pstmt.executeQuery();
            
            Cliente clienteLogado = new Cliente();
            clienteLogado.setId(resultSet.getInt(1));

            if (resultSet.next()) {
                
                String name = resultSet.getString(3);
                TelaInicialCliente telainicialC = new TelaInicialCliente(clienteLogado);
                TelaInicialCliente.lblNomeC.setText(name);
                TelaInicialCliente.emailC.setText(txtLoguin.getText());
                telainicialC.setVisible(true);
                dispose(); // fechar tela de login
                
                pstmt.close();
                conexaoSQlite.desconectar();

            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou Senha inválido");
                pstmt.close();
                conexaoSQlite.desconectar();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_btnLoguinCActionPerformed

    private void txtLoguinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoguinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoguinActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
        TelaCadastroCliente telacadastrocliente = new TelaCadastroCliente();
        telacadastrocliente.setVisible(true);
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaCadastroRestaurante telacadastrorestaurante = new TelaCadastroRestaurante();
        telacadastrorestaurante.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passSenhaActionPerformed

    private void btnLoguinRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoguinRActionPerformed
        // TODO add your handling code here:
        ConexaoSQlite conexaoSQlite = new ConexaoSQlite();
        conexaoSQlite.conectar();

        ResultSet resultSet = null;
        PreparedStatement pstmt = null;

        String sql2 = "SELECT *"
                + " FROM tbl_restaurante"
                + " WHERE emailR = ?"
                + " AND senhaR = ?";
        
        

        try {

            pstmt = conexaoSQlite.criarPreparedStatement(sql2);
            pstmt.setString(1, txtLoguin.getText());
            pstmt.setString(2, passSenha.getText());

            resultSet = pstmt.executeQuery();
            
            Restaurante restauranteLogado = new Restaurante();
            restauranteLogado.setId(resultSet.getInt(1));
            System.out.println(restauranteLogado.getId());
            


            if (resultSet.next()) {
                String name = resultSet.getString(3);
                TelaInicialRestaurante telainicialR = new TelaInicialRestaurante(restauranteLogado);
                telainicialR.setVisible(true);
                TelaInicialRestaurante.lblNomeResta.setText(name);
                this.dispose();
                pstmt.close();
                conexaoSQlite.desconectar();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou Senha inválido");
                conexaoSQlite.desconectar();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnLoguinRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoguin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnLoguinC;
    private javax.swing.JButton btnLoguinR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblLoguin;
    private javax.swing.JPasswordField passSenha;
    private javax.swing.JTextField txtLoguin;
    // End of variables declaration//GEN-END:variables
}
