/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import bd20191.Restaurante;
import conexoes.ConexaoSQlite;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Luiz Cardoso
 */
public class TelaCadastroRestaurante extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroRestaurante
     */
    public TelaCadastroRestaurante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNomeR = new javax.swing.JTextField();
        txtEmailR = new javax.swing.JTextField();
        txtSenhaR = new javax.swing.JTextField();
        txtEndereçoR = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboBoxFrete = new javax.swing.JComboBox<>();
        comboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Cadastro");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ci Food");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 60, 79, 30);
        getContentPane().add(txtNomeR);
        txtNomeR.setBounds(30, 190, 250, 30);
        getContentPane().add(txtEmailR);
        txtEmailR.setBounds(30, 260, 250, 30);
        getContentPane().add(txtSenhaR);
        txtSenhaR.setBounds(30, 320, 250, 30);
        getContentPane().add(txtEndereçoR);
        txtEndereçoR.setBounds(30, 380, 250, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cadastrar Restaurante:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 190, 17);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 530, 130, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 170, 77, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 240, 72, 13);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Senha:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 300, 84, 13);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Endereço: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 360, 72, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Categoria:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 430, 82, 10);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tipo de Frete:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 470, 87, 10);

        comboBoxFrete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboBoxFrete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grátis", "Pago - Valor fixo", " " }));
        comboBoxFrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFreteActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxFrete);
        comboBoxFrete.setBounds(130, 460, 120, 30);

        comboBoxCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lanches", "Brasileira", "Chinesa", "Japonesa", "Pizzas", "Hambúrguer", "Mexicana", "Italiana", "Doceria" }));
        comboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxCategoria);
        comboBoxCategoria.setBounds(130, 420, 120, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2959518_Easy-Resize.com (1).jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-430, -100, 1290, 710);

        setSize(new java.awt.Dimension(863, 646));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxFreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFreteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxFreteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Restaurante restaurante = new Restaurante();
        restaurante.setEmail(txtEmailR.getText());
        restaurante.setEndereco(txtEndereçoR.getText());
        restaurante.setNome(txtNomeR.getText());
        restaurante.setSenha(txtSenhaR.getText());
        restaurante.setId(1);
        restaurante.setTipo_frete(comboBoxFrete.getSelectedItem().toString());
        restaurante.setCategoria(comboBoxCategoria.getSelectedItem().toString());
        restaurante.setSituaçao("fechado");
        
        
        try {
            //SALVAR NO BANCO primeiro conecta
            Class.forName("org.sqlite.JDBC");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastroRestaurante.class.getName()).log(Level.SEVERE, null, ex);
        }
        ConexaoSQlite conexaoSQlite2 = new ConexaoSQlite();
        conexaoSQlite2.conectar();
        
        boolean jaCadastradoR = false;
        ResultSet resultSet = null;
        PreparedStatement pstmt = null;
        
        String sql2 = "SELECT *"
                + " FROM tbl_restaurante"
                + " WHERE emailR = ?";
        
        try {

            pstmt = conexaoSQlite2.criarPreparedStatement(sql2);
            pstmt.setString(1, txtEmailR.getText());

            resultSet = pstmt.executeQuery();

            if (resultSet.next()) {
                
                jaCadastradoR = true;
                pstmt.close();
                conexaoSQlite2.desconectar();
            } else {
                pstmt.close();
                conexaoSQlite2.desconectar();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        conexaoSQlite2.conectar();
        
        if(jaCadastradoR){
            JOptionPane.showMessageDialog(null, "Restaurante já cadastrado!");
        }else{
            //System.out.println(conexaoSQlite2);
        String sqlInsert = "INSERT INTO tbl_restaurante ("
                //+ "id,"  //primary key se tentar inserir 2 do mesmo id da erro
                + "emailR,"
                + "Nome,"
                + "senhaR,"
                + "endereçoR,"
                + "Situação,"
                + "Categoria,"
                + "Frete"
                + ") VALUES(?, ?, ?, ?, ?, ?, ?)"
                + ";";
        if (conexaoSQlite2 == null){
            System.out.println("eh null");
        }
        
        else{
            System.out.println("nao eh null");
        }
        
        PreparedStatement preparedstatement;
        preparedstatement = conexaoSQlite2.criarPreparedStatement(sqlInsert);
        
        if (preparedstatement == null){
            System.out.println("eh null");
        }
        
        else{
            System.out.println("nao eh null");
        }
        
        
        
        try{
            
            
            // COLOCA NA ORDEM DAS INTERROGACOES A PARTIR DA POSICAO 1
            //preparedstatement.setInt(1, cliente1.getId());
            preparedstatement.setString(1, restaurante.getEmail());
            preparedstatement.setString(2, restaurante.getNome());
            preparedstatement.setString(3, restaurante.getSenha());
            preparedstatement.setString(4, restaurante.getEndereco());
            preparedstatement.setString(5, "fechado");
            preparedstatement.setString(6, restaurante.getCategoria());
            preparedstatement.setString(7, restaurante.getTipo_frete());
            
            //retorna um inteiro, se for 1 = inseriu    se for 0 = não inseriu
            int resultado = preparedstatement.executeUpdate();
            System.out.println(resultado);
            
            System.out.println(resultado);
            if (resultado == 1){
                System.out.println("inseriu");
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
            }else{
                System.out.println("nao inseriu");
            }
        
            //fecha statement e fecha conexao
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Erro ao realizar Cadastro");
        } finally { //fechar tudo
                if(preparedstatement != null){
                    try {
                        preparedstatement.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(TelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                conexaoSQlite2.desconectar();
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxCategoria;
    private javax.swing.JComboBox<String> comboBoxFrete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEmailR;
    private javax.swing.JTextField txtEndereçoR;
    private javax.swing.JTextField txtNomeR;
    private javax.swing.JTextField txtSenhaR;
    // End of variables declaration//GEN-END:variables
}
