/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.TelaInicialCliente.lblNomeC;
import bd20191.Restaurante;
import conexoes.ConexaoSQlite;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Luiz Cardoso
 */
public class TelaInicialRestaurante extends javax.swing.JFrame {
    
    Restaurante restauranteLogado;

    /**
     * Creates new form TelaInicialRestaurante
     */
    public TelaInicialRestaurante(Restaurante restauranteLogado) {
        this.restauranteLogado = restauranteLogado;
        initComponents();
    }

    private TelaInicialRestaurante() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void atualizarSituaçãoAberto() {

        String sql = "UPDATE tbl_restaurante"
                + " SET Situação = ?"
                + " WHERE idR"
                + " LIKE ?";
        
        checkBoxFechado.setSelected(false);


        try {
            ConexaoSQlite conexaoSQlite = new ConexaoSQlite();
            conexaoSQlite.conectar();
            PreparedStatement pstmt = conexaoSQlite.criarPreparedStatement(sql);

            //passando o conteudo da caixa de pesquisa para o ? da string
            //atenção ao % que é a continuacao da string
            pstmt.setString(1, checkBoxAberto.getText());
            pstmt.setInt(2, restauranteLogado.getId());
            //pstmt.setString(1, restauranteLogado.getId());
            int resultado = pstmt.executeUpdate();

            System.out.println(resultado);
            if (resultado == 1) {
                System.out.println("inseriu");
                JOptionPane.showMessageDialog(null, "O restaurante está Aberto");
                
            } else {
                System.out.println("nao inseriu");
            }

            pstmt.close();
            conexaoSQlite.desconectar();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    
    private void atualizarSituaçãoFechado() {

        String sql = "UPDATE tbl_restaurante"
                + " SET Situação = ?"
                + " WHERE idR"
                + " LIKE ?";
        
        checkBoxAberto.setSelected(false);

        try {
            ConexaoSQlite conexaoSQlite = new ConexaoSQlite();
            conexaoSQlite.conectar();
            PreparedStatement pstmt = conexaoSQlite.criarPreparedStatement(sql);

            //passando o conteudo da caixa de pesquisa para o ? da string
            //atenção ao % que é a continuacao da string
            pstmt.setString(1, checkBoxFechado.getText());
            pstmt.setInt(2, restauranteLogado.getId());
            //pstmt.setString(1, restauranteLogado.getId());
            int resultado = pstmt.executeUpdate();

            System.out.println(resultado);
            if (resultado == 1) {
                System.out.println("inseriu");
                JOptionPane.showMessageDialog(null, "O restaurante está Fechado");
                
            } else {
                System.out.println("nao inseriu");
            }

            pstmt.close();
            conexaoSQlite.desconectar();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPrato = new javax.swing.JButton();
        lblNomeResta = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        checkBoxAberto = new javax.swing.JCheckBox();
        checkBoxFechado = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Inicial");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ci Food");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 30, 79, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Bem Vindo(a),  ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 131, 110, 17);

        btnPrato.setText("Adicionar Prato");
        btnPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPratoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrato);
        btnPrato.setBounds(10, 410, 112, 21);

        lblNomeResta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomeResta.setText("NOME");
        getContentPane().add(lblNomeResta);
        lblNomeResta.setBounds(117, 131, 167, 17);

        lblData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblData.setText("DATA");
        getContentPane().add(lblData);
        lblData.setBounds(10, 181, 274, 17);

        checkBoxAberto.setText("Aberto");
        checkBoxAberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAbertoActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxAberto);
        checkBoxAberto.setBounds(230, 220, 110, 21);

        checkBoxFechado.setText("Fechado");
        checkBoxFechado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxFechadoActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxFechado);
        checkBoxFechado.setBounds(230, 250, 100, 21);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Editar Cardápio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Emitir Relatórios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Editar Perfil");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Encerrar Sessão");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(370, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPratoActionPerformed
        // TODO add your handling code here:
        TelaAdicionarPrato novoPrato = new TelaAdicionarPrato(restauranteLogado);
        TelaAdicionarPrato.lblNomeRest.setText(lblNomeResta.getText());
        novoPrato.setVisible(true);
    }//GEN-LAST:event_btnPratoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //muda a label para a data atual do sistema
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
        
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        TelaLoguin telaloguin = new TelaLoguin();
        dispose();
        telaloguin.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaLoguin telaloguin = new TelaLoguin();
        dispose();
        telaloguin.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        TelaEditCardápio telaeditc = new TelaEditCardápio(restauranteLogado);
        TelaEditCardápio.lblEditNomeRest.setText(lblNomeResta.getText());
        telaeditc.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        TelaEmitirRelatório telarelatorio = new TelaEmitirRelatório(restauranteLogado);
        telarelatorio.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        TelaPerfilRestaurante telaperfilR = new TelaPerfilRestaurante(restauranteLogado);
        telaperfilR.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        
        String sql = "SELECT *"
                + " FROM tbl_restaurante"
                + " WHERE idR"
                + " LIKE ?";
        
        try{
            ConexaoSQlite conexaoSQlite = new ConexaoSQlite();
            conexaoSQlite.conectar();
            PreparedStatement pstmt = conexaoSQlite.criarPreparedStatement(sql);
            ResultSet resultset = null;
            //passando o conteudo da caixa de pesquisa para o ? da string
            //atenção ao % que é a continuacao da string
            //pstmt.setString(1, txtPesquisarP.getText() + "%");
            pstmt.setInt(1, restauranteLogado.getId());
            resultset = pstmt.executeQuery();
            //faz o preenchimento da tabela com o resultado 'ResultSet'
            lblNomeResta.setText(resultset.getString(3));
            
            pstmt.close();
            conexaoSQlite.desconectar();
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void checkBoxAbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAbertoActionPerformed
        // TODO add your handling code here:
        atualizarSituaçãoAberto();
        System.out.println(checkBoxAberto.getText());
    }//GEN-LAST:event_checkBoxAbertoActionPerformed

    private void checkBoxFechadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxFechadoActionPerformed
        // TODO add your handling code here:
        atualizarSituaçãoFechado();
    }//GEN-LAST:event_checkBoxFechadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrato;
    private javax.swing.JCheckBox checkBoxAberto;
    private javax.swing.JCheckBox checkBoxFechado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblNomeResta;
    // End of variables declaration//GEN-END:variables
}
