/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.TelaAdicionarPrato.lblNomeRest;
import static Interface.TelaCardápio.lblNomeCardapio;
import static Interface.TelaCarrinho.txtAreaCarrinho;
import static Interface.TelaCarrinho.txtValorTotal;
import static Interface.TelaInicialCliente.emailC;
import bd20191.Cliente;
import bd20191.Pedido;
import bd20191.Prato;
import conexoes.ConexaoSQlite;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static Interface.TelaPerfilCliente.txtEditarEmailC;

/**
 *
 * @author Luiz Cardoso
 */
public class TelaEndereço extends javax.swing.JFrame {

    
    private Cliente clienteLogado;
    /**
     * Creates new form TelaEndereço
     */
    public TelaEndereço(Cliente clienteLogado) {
        
        this.clienteLogado = clienteLogado;
        initComponents();
    }

    private TelaEndereço() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }



    
    private void setarEndereço(){
    
        ConexaoSQlite conexaoSQlite = new ConexaoSQlite();
        conexaoSQlite.conectar();

        ResultSet resultSet = null;
        PreparedStatement pstmt = null;

        String sql2 = "SELECT *"
                + " FROM tbl_cliente"
                + " WHERE id_cliente = ?";
        
        try{
            pstmt = conexaoSQlite.criarPreparedStatement(sql2);
            pstmt.setInt(1, clienteLogado.getId());
            resultSet = pstmt.executeQuery();
            String end = resultSet.getString(5);
            txtEndereçoEntrega.setText(end);
            conexaoSQlite.desconectar();
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtObs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtEndereçoEntrega = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ci Food");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText("Meu Endereço");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Complemento / Observação: ");

        btnFinalizar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnFinalizar.setText("Finalizar Pedido");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("Endereço de Entrega (Rua, Número,Bairro): ");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/diagram-06_24511.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtObs)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 204, Short.MAX_VALUE))
                    .addComponent(txtEndereçoEntrega)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(54, 54, 54)))
                .addComponent(txtEndereçoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnFinalizar)
                .addGap(20, 20, 20))
        );

        setSize(new java.awt.Dimension(548, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setarEndereço();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        Date data = new Date();
        DateFormat formatador = new SimpleDateFormat("dd/MM/yyyy HH'h'mm");
        
        
        Pedido novoPedido = new Pedido();
        novoPedido.setValor(txtValorTotal.getText());
        novoPedido.setLocalEntrega(txtEndereçoEntrega.getText());
        novoPedido.setData(formatador.format(data));
        novoPedido.setId(1);
        
        try {
            Class.forName("org.sqlite.JDBC");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaAdicionarPrato.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        //SALVAR NO BANCO primeiro conecta
        ConexaoSQlite conexaoSQlite = new ConexaoSQlite();
        conexaoSQlite.conectar();
        //System.out.println(cliente1.getEndereco());
        String sqlInsert = "INSERT INTO tbl_pedido ("
                //+ "id,"  //primary key se tentar inserir 2 do mesmo id da erro
                + "data_hora,"
                + "local_entrega,"
                + "id_cliente,"
                + "valor,"
                + "nomeRestaurante,"
                + "detalhes"
                + ") VALUES(?, ?, ?, ?, ?, ?)"
                + ";";
        
        PreparedStatement preparedstatement;
        preparedstatement = conexaoSQlite.criarPreparedStatement(sqlInsert);
        System.out.println(novoPedido.getData());
        
        try{
            // COLOCA NA ORDEM DAS INTERROGACOES A PARTIR DA POSICAO 1
            //preparedstatement.setInt(1, cliente1.getId());
            preparedstatement.setString(1, novoPedido.getData().toString());
            preparedstatement.setString(2, novoPedido.getLocalEntrega());
            preparedstatement.setInt(3, clienteLogado.getId());
            preparedstatement.setString(4, novoPedido.getValor());
            preparedstatement.setString(5, lblNomeCardapio.getText());
            preparedstatement.setString(6, txtAreaCarrinho.getText());

            //retorna um inteiro, se for 1 = inseriu    se for 0 = não inseriu
            int resultado = preparedstatement.executeUpdate();
            
            System.out.println(resultado);
            if (resultado == 1){
                System.out.println("inseriu");
                JOptionPane.showMessageDialog(null, "Pedido concluído com sucesso");
            }else{
                System.out.println("nao inseriu");
            }
        
        } catch(SQLException e){
            //JOptionPane.showMessageDialog(null, "Erro ao realizar Pedido");
            Logger.getLogger(TelaCadastroCliente.class.getName()).log(Level.SEVERE, null, e);
        } finally { //fechar tudo
                if(preparedstatement != null){
                    try {
                        preparedstatement.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(TelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                conexaoSQlite.desconectar();
            }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEndereço.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEndereço.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEndereço.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEndereço.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEndereço().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEndereçoEntrega;
    private javax.swing.JTextField txtObs;
    // End of variables declaration//GEN-END:variables
}
