/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.TelaEditCardápio.tblEditPratos;
import bd20191.Cliente;
import conexoes.ConexaoSQlite;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Luiz Cardoso
 */
public class TelaPerfilCliente extends javax.swing.JFrame {
    
    private Cliente clienteLogado;
    /**
     * Creates new form TelaPerfilCliente
     */
    public TelaPerfilCliente(Cliente clienteLogado) {
        
        this.clienteLogado = clienteLogado;
        initComponents();
    }

    private TelaPerfilCliente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
        private void setarInformações(){
    
        ConexaoSQlite conexaoSQlite = new ConexaoSQlite();
        conexaoSQlite.conectar();

        ResultSet resultSet = null;
        PreparedStatement pstmt = null;

        String sql2 = "SELECT *"
                + " FROM tbl_cliente"
                + " WHERE id_cliente = ?";
        
        try{
            pstmt = conexaoSQlite.criarPreparedStatement(sql2);
            pstmt.setInt(1, clienteLogado.getId());
            resultSet = pstmt.executeQuery();
            String editemail = resultSet.getString(2);
            txtEditarEmailC.setText(editemail);
            String editnome = resultSet.getString(3);
            txtEditarNomeC.setText(editnome);
            String editsenha = resultSet.getString(4);
            txtEditarSenhaC.setText(editsenha);
            String end = resultSet.getString(5);
            txtEditarEndereçoC.setText(end);
            conexaoSQlite.desconectar();
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
        
        //metodo para editar informações
        private void atualizarInformações() {

        String sql = "UPDATE tbl_cliente"
                + " SET nome = ?,"
                + " email = ?,"
                + " senha = ?,"
                + " endereco = ?"
                + " WHERE id_cliente"
                + " LIKE ?";


        try {
            ConexaoSQlite conexaoSQlite = new ConexaoSQlite();
            conexaoSQlite.conectar();
            PreparedStatement pstmt = conexaoSQlite.criarPreparedStatement(sql);

            //passando o conteudo da caixa de pesquisa para o ? da string
            //atenção ao % que é a continuacao da string
            pstmt.setString(1, txtEditarNomeC.getText());
            pstmt.setString(2, txtEditarEmailC.getText());
            pstmt.setString(3, txtEditarSenhaC.getText());
            pstmt.setString(4, txtEditarEndereçoC.getText());
            pstmt.setInt(5, clienteLogado.getId());
            //pstmt.setString(1, restauranteLogado.getId());
            int resultado = pstmt.executeUpdate();

            System.out.println(resultado);
            if (resultado == 1) {
                System.out.println("inseriu");
                JOptionPane.showMessageDialog(null, "Informações Atualizadas");
                dispose();
            } else {
                System.out.println("nao inseriu");
            }

            pstmt.close();
            conexaoSQlite.desconectar();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEditarNomeC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEditarEmailC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEditarSenhaC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEditarEndereçoC = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Editar Informações do Perfil:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 220, 256, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/profile-icon_34378.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 31, 164, 148);

        jLabel3.setText("Nome: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 294, 98, 13);
        getContentPane().add(txtEditarNomeC);
        txtEditarNomeC.setBounds(10, 317, 284, 30);

        jLabel4.setText("Email: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 354, 110, 13);
        getContentPane().add(txtEditarEmailC);
        txtEditarEmailC.setBounds(10, 377, 284, 30);

        jLabel5.setText("Senha:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 414, 77, 13);
        getContentPane().add(txtEditarSenhaC);
        txtEditarSenhaC.setBounds(10, 437, 284, 30);

        jLabel6.setText("Endereço:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 482, 116, 13);
        getContentPane().add(txtEditarEndereçoC);
        txtEditarEndereçoC.setBounds(10, 505, 284, 30);

        btnSalvar.setText("Salvar Informações");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(242, 582, 150, 21);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/diskette_save_saveas_1514.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(203, 572, 35, 42);

        setSize(new java.awt.Dimension(414, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        setarInformações();
    }//GEN-LAST:event_formWindowActivated

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        atualizarInformações();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPerfilCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JTextField txtEditarEmailC;
    private javax.swing.JTextField txtEditarEndereçoC;
    private javax.swing.JTextField txtEditarNomeC;
    private javax.swing.JTextField txtEditarSenhaC;
    // End of variables declaration//GEN-END:variables
}
